#!/bin/bash

commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -qE "^(build|ci|docs|feat|fix|refactor|style|test)(\(.+\))?(\!)?\: .{1,100}$"; then
  echo "****************************************************"
  echo "Invalid commit message format. Expected format is '<type>: <subject>'."
  exit 1
fi